# fly.toml app configuration file generated for hun0219 on 2024-08-30T18:10:23+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hun0219'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
